MULE-19232: Add a read timeout to the pipe used by http client to stream responses
mulesoft/mule-http-service pull request #324
Opened 2021-02-23 17:31 UTC by eze210

2021-02-23 18:47 UTC, aiannucci commented
--validate

2021-02-24 17:37 UTC, eze210 commented
--validate

2021-02-24 19:25 UTC, eze210 commented
--validate

2021-02-24 20:36 UTC, szaffarano commented
--validate

2021-02-25 12:18 UTC, eze210 commented
--validate

2021-02-26 18:58 UTC, fsgonz requested changes

2021-02-26 18:58 UTC, fsgonz commented on src/main/java/org/mule/service/http/impl/util/TimedPipedInputStream.java
> + */
add since.

2021-02-26 18:58 UTC, fsgonz commented on src/main/java/org/mule/service/http/impl/util/TimedPipedOutputStream.java
> +public class TimedPipedOutputStream extends OutputStream {
add jdoc since.

2021-02-26 18:58 UTC, fsgonz commented on src/test/java/org/mule/service/http/impl/util/TimedPipedInputStreamTestCase.java
> +public class TimedPipedInputStreamTestCase {
add allure annotations

2021-02-26 18:58 UTC, fsgonz commented on src/test/java/org/mule/service/http/impl/util/TimedPipedInputStreamTestCase.java
> +  public void throwsExceptionAfterTimeoutWhenRequestingByte() throws IOException {
Maybe you can add @Issue in the tests related to timeout behavior.

2021-02-26 19:24 UTC, fsgonz approved these changes

2021-02-26 21:05 UTC, merged