MULE-19181: Use the right ClassLoader to handle HTTP requests
mulesoft/mule-http-service pull request #333
Opened 2021-04-07 18:36 UTC by eze210

2021-04-13 20:01 UTC, fsgonz requested changes

2021-04-13 20:01 UTC, fsgonz commented on src/test/java/org/mule/service/http/impl/service/server/grizzly/AbstractGrizzlyServerManagerTestCase.java
> +      server.addRequestHandler("/path", (requestContext, responseCallback) -> {
I would set the path o a constant.

2021-04-13 20:52 UTC, eze210 commented on src/main/java/org/mule/service/http/impl/service/server/grizzly/GrizzlyHttpServer.java
> +  private static boolean REPLACE_CONTEXT_CLASSLOADER = getProperty(MULE_LOG_SEPARATION_DISABLED) == null;
The property already exists

2021-04-13 20:52 UTC, eze210 commented on src/main/java/org/mule/service/http/impl/service/server/grizzly/GrizzlyHttpServer.java
> +      public ClassLoader getContextClassLoader() {
If it ins't necessary, the setter doesn't do anything

2021-04-14 12:49 UTC, eze210 commented on src/test/java/org/mule/service/http/impl/service/server/grizzly/AbstractGrizzlyServerManagerTestCase.java
> +      server.addRequestHandler("/path", (requestContext, responseCallback) -> {
Done :)

2021-04-14 15:18 UTC, fsgonz approved these changes

2021-04-14 15:46 UTC, merged