MULE-19908: set correct query params in redirect URI
mulesoft/mule-http-service pull request #408
Opened 2021-11-03 12:56 UTC by jcgrethe

2021-11-04 15:40 UTC, eze210 commented
--validate

2021-11-04 16:12 UTC, fsgonz requested changes

2021-11-04 16:12 UTC, fsgonz commented on src/main/java/org/mule/service/http/impl/service/client/GrizzlyHttpClient.java
> +  private static final String ENABLE_MULE_REDIRECT_PROPERTY_NAME = SYSTEM_PROPERTY_PREFIX + "http.EnableMuleRedirect";
use camelCase for thesystem property part.

2021-11-04 16:12 UTC, fsgonz commented on src/main/java/org/mule/service/http/impl/service/client/GrizzlyHttpClient.java
> +  private static final String ENABLE_MULE_REDIRECT_PROPERTY_NAME = SYSTEM_PROPERTY_PREFIX + "http.EnableMuleRedirect";
Add an explanation for this property.

2021-11-04 16:12 UTC, fsgonz commented on src/main/java/org/mule/service/http/impl/service/client/GrizzlyHttpClient.java
> +      builder.setFollowRedirects(!enableMuleRedirect && options.isFollowsRedirect());
Does this mean that now, by default we are delegating the redirect logic to grizzly as before MULE-19622? 
Explain this in a comment for the system property.

2021-11-04 16:12 UTC, fsgonz commented on src/test/java/org/mule/service/http/impl/service/util/RedirectUtilsTestCase.java
> +    responseHeaders.removeAll(LOCATION);
duplicate code. Create a method with the appropriate parameters.

2021-11-04 16:24 UTC, fsgonz commented on src/main/java/org/mule/service/http/impl/service/client/GrizzlyHttpClient.java
> +      builder.setFollowRedirects(!enableMuleRedirect && options.isFollowsRedirect());
The answer is yes as indicated in the comment for the system property.

2021-11-04 16:27 UTC, fsgonz approved these changes

2021-11-04 16:28 UTC, fsgonz submitted a review, later dismissed

2021-11-04 16:45 UTC, eze210 commented
--validate

2021-11-04 18:06 UTC, eze210 commented
--validate

2021-11-04 18:15 UTC, jcgrethe commented
--validate

2021-11-04 19:51 UTC, anosenzo commented
--validate

2021-11-04 20:17 UTC, jcgrethe commented
--validate

2021-11-04 20:42 UTC, jcgrethe commented
--validate

2021-11-04 21:31 UTC, fsgonz approved these changes

2021-11-04 22:10 UTC, merged

2022-04-14 19:05 UTC, chris-ebert reviewed
Per HTTP 1.1 spec, 302 should use the request method. If a client needs it to change to GET, we should have a flag we can set for them to keep the non-spec behavior. We should also ask them to fix it.