W-12161504: Fix Cookie replacement during redirect mechanism
mulesoft/mule-http-service pull request #486
Opened 2022-12-28 17:32 UTC by eze210

2022-12-28 19:16 UTC, jcgrethe requested changes

2022-12-28 19:16 UTC, jcgrethe commented on src/test/java/org/mule/service/http/impl/service/util/RedirectUtilsTestCase.java
> +        requestBuilder.build().getCookies().stream().map(Cookie::toString).collect(Collectors.toList());
static import

2022-12-28 19:16 UTC, jcgrethe commented on src/test/java/org/mule/service/http/impl/service/util/RedirectUtilsTestCase.java
> +        requestBuilder.build().getCookies().stream().map(Cookie::toString).collect(Collectors.toList());
static import

2022-12-28 19:16 UTC, jcgrethe commented on src/test/java/org/mule/service/http/impl/service/util/RedirectUtilsTestCase.java
> +        requestBuilder.build().getCookies().stream().map(Cookie::toString).collect(Collectors.toList());
static import

2022-12-28 19:59 UTC, jcgrethe approved these changes

2022-12-29 12:17 UTC, eze210 commented
--validate

2022-12-29 17:55 UTC, merged