W-13754230: Clear requestBuilders after response is received to avoid…
mulesoft/mule-http-service pull request #539
Opened 2023-08-09 17:22 UTC by hyerans

… OOM

2023-08-10 16:44 UTC, fsgonz submitted a review, later dismissed

2023-08-22 15:59 UTC, eze210 requested changes

2023-08-22 15:59 UTC, eze210 commented on src/main/java/org/mule/service/http/impl/service/client/GrizzlyHttpClient.java
> +   * @param redirectRequest the {@link Request} involved in the redirect.
If some exception is found during the execution of the redirect, this argument will be null. (add this clarification)

2023-08-22 17:36 UTC, eze210 approved these changes

2023-08-22 19:06 UTC, merged